[package]
name = "rusty-rogue"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
crossterm = {version = "0.26.1", features = ["serde"]}
ratatui = { version = "0.21.0", features = ["all-widgets"] }
serde = {version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
